library("devtools")
install_github(repo="BBmisc", username="berndbischl")
install_github(repo="checkmate", username="mllg")
install_github(repo="ParamHelpers", username="berndbischl")
install_github(repo="parallelMap", username="berndbischl")
install_github(repo="mlr", username="berndbischl")
install_github(repo="mlrMBO", username="berndbischl")
install_github(repo="BatchExperiments", username="tudo-r")
install_github(repo="BatchJobs", username="tudo-r")